Completed css-brochure-form
Eugenepark215/c0822-code-solutions pull request #18
Opened 2022-08-25 03:41 UTC by Eugenepark215

2022-08-25 03:50 UTC, thebearingedge requested changes
screenshot plz

2022-08-25 04:16 UTC, Eugenepark215 commented
![Screen Shot 2022-08-24 at 9 16 19 PM](https://user-images.githubusercontent.com/97265272/186573655-953c5c08-1879-4006-af04-96d51fef8f6d.png)

2022-08-26 15:00 UTC, thebearingedge requested changes
Ok, looking good, we just need to address the border style of your inputs and buttons. the default is a weird faux 3d effect, but for the inputs we want solid borders and for the button we want no border.

2022-08-28 17:48 UTC, thebearingedge approved these changes

2022-08-28 21:44 UTC, merged