Css three column layout
Eugenepark215/c0822-code-solutions pull request #20
Opened 2022-08-25 21:35 UTC by Eugenepark215

<img width="1440" alt="Screen Shot 2022-08-25 at 2 33 51 PM" src="https://user-images.githubusercontent.com/97265272/186773235-090c1918-059a-454f-8017-5dfafec03ba7.png">

2022-08-25 21:49 UTC, thebearingedge requested changes
Ok, looking pretty good so far, but we can improve the structure of the HTML from here. Instead of putting `display: flex` on your `.container`, move it to `.row` your basic structure should be something like this. One container, one row, and three columns.

```html
<div class="container">
  <div class="row">
    <div class="column">
      <-- image, heading, and paragraph -->
    </div>
    <div class="column">
      <-- image, heading, and paragraph -->
    </div>
    <div class="column">
      <-- image, heading, and paragraph -->
    </div>
  </div>
</div>
```

2022-08-25 22:33 UTC, Eugenepark215 commented
<img width="1440" alt="Screen Shot 2022-08-25 at 3 32 24 PM" src="https://user-images.githubusercontent.com/97265272/186780258-6d171cea-b10c-45e9-9e0d-7077af204262.png">

2022-08-25 23:02 UTC, thebearingedge requested changes
ok, the html is waaaayy, better. we just need some tweaks to the css. no rush

2022-08-25 23:02 UTC, thebearingedge commented on css-three-column-layout/styles.css
> +  flex-basis: calc(100%/3);
flex-basis only goes on flex items, so you can move this to your `.column` rule set.

2022-08-25 23:02 UTC, thebearingedge commented on css-three-column-layout/styles.css
>  section {
To get the images dead center in the sections, you can use flexbox (see css-flexbox/align-items.html)

2022-08-25 23:33 UTC, Eugenepark215 commented
<img width="1440" alt="Screen Shot 2022-08-25 at 4 30 29 PM" src="https://user-images.githubusercontent.com/97265272/186786775-ecf9bbaa-cb8e-48d0-bfa1-83a751048771.png">

2022-08-26 14:40 UTC, thebearingedge approved these changes

2022-08-26 15:45 UTC, merged