Css canvas medical
Eugenepark215/c0822-code-solutions pull request #22
Opened 2022-08-28 01:53 UTC by Eugenepark215

<img width="1440" alt="Screen Shot 2022-08-27 at 6 52 04 PM (2)" src="https://user-images.githubusercontent.com/97265272/187054122-f1b6685b-0387-4208-9c76-4ce96c934151.png">
<img width="1440" alt="Screen Shot 2022-08-27 at 6 51 05 PM (2)" src="https://user-images.githubusercontent.com/97265272/187054126-1a232bf2-6973-4b7b-8b4e-bd088ae8d132.png">
<img width="1440" alt="Screen Shot 2022-08-27 at 6 51 15 PM (2)" src="https://user-images.githubusercontent.com/97265272/187054127-42780699-d300-4400-beb6-2c076fdad761.png">

2022-08-28 18:06 UTC, thebearingedge requested changes
Ok, great job so far. We can make some improvements though. 

1. Instead of naming all of your columns based on their order, name them based on how big they are (column-half, column-one-fourth, column-full).
2. Don't use a bunch of left margin to push things to the middle of the page. Instead, make the row have a `max-width` and a `margin: 0 auto` so it centers on the page.

We'll start there.

2022-08-29 05:13 UTC, Eugenepark215 commented
![Screen Shot 2022-08-28 at 10 13 17 PM](https://user-images.githubusercontent.com/97265272/187127669-a45af2c9-f4cd-4a25-9907-10bd374a74ca.png)

2022-08-29 17:35 UTC, codingcodymiller requested changes
Hey Eugene! One significant note for this version: There should only be a single `row` class, not a variant class for each row you use. You should make one `row` class with only `display: flex` applied to it and make additional classes for any unique styling needed for specific elements that you can add to the element in addition to the `row` class.

2022-08-29 22:45 UTC, codingcodymiller requested changes
Please update your other `row` variant classes, as well 🙏

2022-08-30 21:55 UTC, codingcodymiller requested changes
Just submitting another review so I know when this is actually ready to be reviewed again 🤓

2022-09-07 22:27 UTC, codingcodymiller requested changes

2022-09-07 22:27 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="row-clinicians">
Same here, no specific `row` classes for specific sections.

2022-09-07 22:27 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="row-ready">
Same here, no specific `row` classes for specific sections.

2022-09-07 22:27 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="row-contact">
Same here, no specific `row` classes for specific sections.

2022-09-07 22:27 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="row-privacy">
Same here, no specific `row` classes for specific sections.

2022-10-14 17:14 UTC, thebearingedge approved these changes
Nice work! 👍

2022-10-14 17:30 UTC, merged