Javascript light bulb
Eugenepark215/c0822-code-solutions pull request #46
Opened 2022-09-07 02:14 UTC by Eugenepark215

![Screen Shot 2022-09-06 at 7 12 33 PM](https://user-images.githubusercontent.com/97265272/188773518-2089c35d-a4da-4b29-8693-e36b72bcb77e.png)
![Screen Shot 2022-09-06 at 7 12 37 PM](https://user-images.githubusercontent.com/97265272/188773529-4d65aacf-2f62-4b89-8cd2-c059044045e2.png)

2022-09-07 16:14 UTC, codingcodymiller requested changes

2022-09-07 16:14 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if (click % 2 === 0) {
To determine whether to turn the light on or off, you are making a counter, but the only thing you ever care about is if the counter's value was even or odd. This is a situation where you would be better off using a boolean to keep track of if the light is currently on.

2022-09-08 15:42 UTC, codingcodymiller requested changes

2022-09-08 15:42 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if (lightBulb.className === 'lightbulb-off') {
Now your logic is dependent on the state of the DOM to know what to do, which is less than ideal. You should follow my initial suggestion of using a variable containing a boolean value to keep track of if the light is currently on or not, and use that variable's value to decide what action to take when the lightbulb is clicked.

2022-09-08 17:10 UTC, Eugenepark215 commented
In progress

2022-09-08 19:21 UTC, Eugenepark215 commented
Ready for review

2022-09-09 17:35 UTC, codingcodymiller approved these changes

2022-09-09 18:53 UTC, merged