Html forms
Eugenepark215/c0822-code-solutions pull request #9
Opened 2022-08-23 17:18 UTC by Eugenepark215

2022-08-23 17:19 UTC, Eugenepark215 commented
<img width="1440" alt="Screen Shot 2022-08-23 at 10 19 22 AM" src="https://user-images.githubusercontent.com/97265272/186223734-96c7eb51-e7ee-40e6-81b3-e8e516cee0c2.png">

2022-08-23 17:37 UTC, thebearingedge requested changes
Ok, great, much better so far. It just needs some `<label>` elements for each input.

![image](https://user-images.githubusercontent.com/7432943/186226975-56698236-0f0d-459c-8724-cbcf38f7f46f.png)

2022-08-23 22:58 UTC, thebearingedge requested changes
Ok, sweet, now each form control element (input, select, radio, textarea) just needs an id attribute to match its label's `for`

2022-08-24 15:21 UTC, thebearingedge requested changes
Here is an example of setting up label `for` and input `id` to match. You'll know it's working when you can click on the label to activate the input.

https://codepen.io/thebearingedge/pen/ExEJPjz?editors=1000

2022-08-24 15:21 UTC, thebearingedge commented on html-forms/index.html
> +        <select name="option" id="option">
The `for` and `id` attribute values will need to match for the label to be clickable.

2022-08-24 15:21 UTC, thebearingedge commented on html-forms/index.html
> +        <input type="radio" name="language" value="JavaScript"/><label for="JavaScript">JavaScript</label>
Each of your radio buttons will need an `id` attribute that matches its label's `for` value.

2022-08-24 15:21 UTC, thebearingedge commented on html-forms/index.html
> +        <textarea name="comments" cols="35" rows="8"></textarea>
Your `textarea` needs an `id` attribute with a value matching the label's `for` value.

2022-08-25 15:05 UTC, thebearingedge approved these changes

2022-08-25 15:38 UTC, merged